import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import AssetsContainer from './AssetsContainer';
import styles from './assets.module.scss';

const Assets: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.assetsPage} container-page`}>
        <AssetsContainer />
      </main>

    </div>
  )
}

export default Assets;
