import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import FormInput from '../components/Input'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <FormInput
          label='enter password'
          type='password'
          name='password'
          endIcon={<Image src='/images/eye.svg' width={24} height={24} />}
        />
      </main>
    </div>
  )
}

export default Home
