import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from './send.module.scss';
import Link from 'next/link';
import Image from 'next/image';
import FormInput from '../../components/Input/Input';
import Button from '../../components/Button/Button';

const Send: NextPage = () => {
  return(
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.sendPage} container-page`}>
        <div className="send-page__header">
          <span className="icon"> 
            <Link href="/wallet">
              <Image src='/images/chevron-left.svg' width={24} height={24} />
            </Link>
          </span>
          Send Assets
        </div>
        <div className="send-page__content">
          <form>
            <FormInput
              label='From'
              type='text'
              name='fromWallet'
              disabled
            />
            <FormInput
              label='To'
              type='text'
              name='toWallet'
            />
            <FormInput
              label='Asset'
              type='text'
              name='asset'
              disabled
              extraClass='asset'
              startIcon={
                <>
                  <Image src='/images/dollar.png' width={24} height={24} />
                  <span className='currency'>USD</span>
                </>
              }
              endIcon={<Image src='/images/layers.svg' width={24} height={24} />}
            />
            <FormInput
              label={
                <>
                  Amount
                  <strong>available: 50 EUR</strong>
                </>
              }
              type='number'
              name='amount'
              endIcon={<span className="max-account">Max</span>}
              extraClass='max-account'
            />
            <div className="group-btn">
              <Button extraClass='outline'>Cancel</Button>
              <Button extraClass='primary'>Send</Button>
            </div>
          </form>
        </div>
      </main>
    </div>
  )
}

export default Send;
