import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import styles from './wallet.module.scss';
import WalletHeader from './components/WalletHeader';
import WalletInfo from './components/WalletInfo';
import WalletActions from './components/WalletActions';
import WalletAssets from './components/WalletAssets';

const Wallet: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.walletPage} container-page`}>
        <div className='bg-wallet'>
          <Image src='/images/bg-wallet.png' width={333} height={343} />
        </div>
        <WalletHeader />
        <WalletInfo />
        <WalletActions />
        <WalletAssets />
      </main>
    </div>
  )
}

export default Wallet
