import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import WalletContainer from '../../containers/WalletContainer'
import styles from './wallet.module.scss';

const Wallet: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.walletPage} container-page`}>
        <WalletContainer />
      </main>

    </div>
  )
}

export default Wallet
