import React, { useCallback, useState } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import styles from './wallet.module.scss';
import WalletHeader from './components/WalletHeader';
import WalletInfo from './components/WalletInfo';
import WalletActions from './components/WalletActions';
import WalletAssets from './components/WalletAssets';
import { useWalletInfo } from '../../hooks/useWalletInfo';
import Modal from '../../components/Modal';
import ModalAssets from './components/ModalAssets';

const Wallet: NextPage = () => {
  const { data, error, changeAsset } = useWalletInfo();
  const [show, setShow] = useState(true);
  const handleChangeAsset = useCallback((currency) => {
    changeAsset(currency)
  }, [])

  if(!data) return null;
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.walletPage} container-page`}>
        <div className='bg-wallet'>
          <Image src='/images/bg-wallet.png' width={333} height={343} />
        </div>
        <WalletHeader />
        <WalletInfo data={data}/>
        <WalletActions />
        <WalletAssets data={data} onChangeAsset={handleChangeAsset} />
        {show ? <ModalAssets data={data} onChangeAsset={handleChangeAsset} handleHide={() => setShow(false)} /> : null }
      </main>

    </div>
  )
}

export default Wallet
